# Generated by Django 4.0.5 on 2022-06-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogger_id_alter_categoria_id_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='contraseña',
        ),
    ]
