# Generated by Django 4.0.5 on 2022-06-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogger_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='bloggers_img'),
        ),
    ]
